# Generated by Django 4.0 on 2021-12-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
    ]
